<<<<<<< HEAD
#Update all the sections by editing the data.yml file inside _data folder.

# Site Settings
title: My Resume
url: 'http://webjeda.com'
baseurl: '/online-cv' #change it according to your repository name
# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: blue # blue turquoise green berry orange ceramic
=======
title: Kim Seung-ju
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://chimaek.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/
>>>>>>> f9c9d82db94dc2eaa1827b2bb0594000a00e6c6f

# Tracker
analytics: UA-83979019-1

<<<<<<< HEAD
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
=======
navigation: https://chimaek.github.io
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: pipiru100@gmail.com
>>>>>>> f9c9d82db94dc2eaa1827b2bb0594000a00e6c6f

# Development Settings
port: 4000
host: 0.0.0.0
safe: false