<<<<<<< HEAD
title: Kim Seung-ju
=======
title: Kim Seunug-ju
>>>>>>> 9d592df9127a96b6311fd17d8c6c8eb961fb307c
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: https://chimaek.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: brianmaierjr
   twitter: brianmaierjr
   facebook: brianmaierjr
   email: pipiru100@gmail.com

google_analytics: "UA-58263416-1"
